### ISSUE TITLE
Add a copy of the MIT license to the repository

### ISSUE THREAD

**Issue by Calinou** [HellboyHeaven/AdvancedCharacter#1]
The asset submission says the asset's license is MIT. Please add a copy of the MIT license to the repository to confirm this :slightly_smiling_face:

**Comment by HellboyHeaven** [comment]
I added. Check please

сб, 2 нояб. 2024 г., 17:33 Hugo Locurcio ***@***.***>:

**Comment by HellboyHeaven** [comment]
I added

**Comment by Calinou** [comment]
Thanks! The asset is now approved: https://godotengine.org/asset-library/asset/3474
